### PR TITLE
Few roles modifications

### PR DESCRIPTION
**Pull request by gillesdubois**
Hi,

We added some functionnalities to your ansible role : 
- Added github repo support (Instead of launchpad)
- Added ssl option support
- Cpan initialization support (This won't block the install if cpan isn't initialized)
- Remove tmp files after the install

Regards,
Gilles Dubois.

### CODE REVIEW

**Comment by franlr** [comment]
Hi,

I'm afraid I must reject this first pull request. I've reviewed these updates today but there are several mistakes into the code. By example:
- `ocs_ssl` is not defined into _defaults/main.yml_ and no value is assigned.
- Lint errors (one blank space instead of two under `name:`, etc).
- Issues I've found in _tasks/main.yml_:
1. syntax error on #L25: `msg="` instead of `msg:"`.
2. syntax error on #L26: It shoud be _get_ocsinventory_agent_ (a missing second underscore).
3. Don't add `{{ocs_ca}}` into #L70 if `ocs_ssl` is _false_. I've tested with a new local fact like `"{{ ocs_final_options}}={{ocs_options} {{ocs_ca}}"` in the conditionals #L43 and #L48.
   For instance:

``` yaml
- name: HTTP URL
    set_fact: >
      ocs_url="http://{{ ocs_server }}"
      ocs_final_options="{{ ocs_options }} --nossl"
    when: ocs_ssl == false

- name: HTTPS URL
  set_fact: >
    ocs_url="https://{{ ocs_server }}"
    ocs_ca="--ca={{ ocs_configdir }}/cacert.pem"
    ocs_final_options="{{ ocs_options }} {{ ocs_ca }}"
  when: ocs_ssl == true
```

Please use double-quote to start and close the references to role's variables like `"{{ocs_configdir}}"` and single-quote to command actions like #L55 and #L70.

Don't hesitate to contact me if you need a clarification.

Regards!
Fran LR

**Comment by gillesdubois** [comment]
Hi,

Sorry we didn't pushed everything a fix is on the way. I will update the PR asap.

Thanks you,
Gilles Dubois.

**Comment by gillesdubois** [comment]
Hi we updated our pull request.
However some thing are still WIP some changes will be made soon.

Regards,
Gilles Dubois.

**Comment by franlr** [comment]
Good job!

**Comment by Neustradamus** [comment]
@gillesdubois: Can you add "Issues" section in OCSInventory-NG org?
- https://github.com/OCSInventory-NG/Ansible-Role-For-UnixAgent

**Pull request merged**
